# TX00DQ05-3001 Reinforcement Learning, exercises 1

In [1]:
# import numpy and other useful packages
import numpy as np
import numpy.linalg as LA

## Weather example

P is the transition matrix and t0 weather on day 0

In [2]:
P = np.array(([0.2, 0.8], [0.6, 0.4]))
t0 = np.array([0.0, 1.0])

t1 = np.dot(t0, P)
print(t1)
t2 = np.dot(t1, P)
print(t2)
print(np.dot(t0, LA.matrix_power(P, 2)))
print(np.dot(t0, LA.matrix_power(P, 10)))
print(np.dot(t0, LA.matrix_power(P, 30)))
print(np.dot(t0, LA.matrix_power(P, 50)))

[0.6 0.4]
[0.36 0.64]
[0.36 0.64]
[0.42852649 0.57147351]
[0.42857143 0.57142857]
[0.42857143 0.57142857]


## Exercise 1

Check some matrix algebra identities with numpy.

* A + B = B + A
* cA + cB = c(A + B) where c is scalar
* if shape of A is (x,y), shape of A.T (transpose) is (y,x) 
* if v is vector of shape (x,), then v dot A has shape (y,)
* verify that shape of A.T dot B is (y, y) and shape of A dot B.T is (x, x)

In [3]:
A = np.array(([1, 2, 3], [2, 0 ,2], [3, 0, 1], [4, 1 ,0]))
B = np.array(([0, 1, 2], [2, 1, 1], [2, 1, 0], [1, 2, 3]))
c = 5.0
# YOUR CODE HERE
v= np.array( ([2,3,4,5]    )  )



print('A+B was: \n',A+B)  ##•A + B = B + A
print('')
print('B+A was: \n', B+A)
print('looks the same')

print('') ##•cA + cB = c(A + B) where c is scalar
print('c*A + c*B was: \n', c*A + c*B)
print('')
print( 'c*(A+B) was:\n',c*(A+B) )
print('looks the same')


print('') ##•if shape of A is (x,y), shape of A.T (transpose) is (y,x) 
print('A was: \n',A)
print('')
print('A.T was: \n',A.T)
print('')
print('A shape was', A.shape)
print('A.T shape was', A.T.shape)
print('looks ok to me, 2nd row 1st col -> 1st row 2nd col, \n \
and 3rd row 1st col -> 1st row 3rd col etc...')


print('')  ##•if v is vector of shape (x,), then v dot A has shape (y,)
print('v shape was: ',v.shape )
print('v was: \n', v)
print('v.dotA shape was: ', (v.dot(A)).shape )
print('')
print('v.dotA was: \n', v.dot(A))
print('as a sidenote, you can doublecheck it with matrix multiplication rules if the A =4x3matrix,\n \
, and v.dotA= 1x3 matrix, \n \
then it follows that v itself must have been= 1x4 matrix (or rather vector) (assuming you want the operation to be legally defined)')


print('A.T.dot(B) shape was: ', A.T.dot(B).shape)##•verify that shape of A.T dot B is (y, y) and shape of A dot B.T is (x, x)
print('A.dot(B.T) shape was: ', A.dot(B.T).shape)
print('looks ok to me')

A+B was: 
 [[1 3 5]
 [4 1 3]
 [5 1 1]
 [5 3 3]]

B+A was: 
 [[1 3 5]
 [4 1 3]
 [5 1 1]
 [5 3 3]]
looks the same

c*A + c*B was: 
 [[ 5. 15. 25.]
 [20.  5. 15.]
 [25.  5.  5.]
 [25. 15. 15.]]

c*(A+B) was:
 [[ 5. 15. 25.]
 [20.  5. 15.]
 [25.  5.  5.]
 [25. 15. 15.]]
looks the same

A was: 
 [[1 2 3]
 [2 0 2]
 [3 0 1]
 [4 1 0]]

A.T was: 
 [[1 2 3 4]
 [2 0 0 1]
 [3 2 1 0]]

A shape was (4, 3)
A.T shape was (3, 4)
looks ok to me, 2nd row 1st col -> 1st row 2nd col, 
 and 3rd row 1st col -> 1st row 3rd col etc...

v shape was:  (4,)
v was: 
 [2 3 4 5]
v.dotA shape was:  (3,)

v.dotA was: 
 [40  9 16]
as a sidenote, you can doublecheck it with matrix multiplication rules if the A =4x3matrix,
 , and v.dotA= 1x3 matrix, 
 then it follows that v itself must have been= 1x4 matrix (or rather vector) (assuming you want the operation to be legally defined)
A.T.dot(B) shape was:  (3, 3)
A.dot(B.T) shape was:  (4, 4)
looks ok to me


## Exercise 2

Throw a dice (1..6) repeadetly and maintain the mean value of the 
numbers continously (and without explicitly storing the numbers or their sum) by
computing a correction factor to the previous mean.

Hint: mean(n) = sum(n) / n = (sum(n-1) + a(n)) / n = (mean(n-1) * (n-1) + a(n)) / n =
mean(n-1) + (a(n) - mean(n-1)) / n

Stop computation when correction factor stays below eps for b rounds or if you reach maxiter iterations.

How does changing eps and b influence the number of iterations needed?

In [4]:
eps = 0.00001
b = 50
maxiter = 1000000

# YOUR CODE HERE

i = 1.0 
mean = 0
corr = 0
stopcounter = 0

for i in range(1, maxiter+1):
    dice = np.random.randint(1,7) ##first dice throw == first mean
    #print('dice was: ',dice , '\n ')
    if i == 1:
        mean = dice
        corr = 0  ## first corr == 0
    else:
        corr = (( dice - mean) / i )
        mean = mean + corr
        if abs(corr) < eps:
            stopcounter += 1
        else:
            stopcounter = 0
    if stopcounter >= b:
        break
        
        
print('you did iterations == ', i)
print('mean == ', mean)
print('corr == ', corr)
            





you did iterations ==  250083
mean ==  3.500265911717274
corr ==  5.996969347185029e-06


In [5]:
def getMeanFromReturns(oldMean, n, curVal):
    newMean = 0
    if  n == 0 and oldMean == 0:
        return newMean
    elif n == 1:
        return curVal
    elif n >= 2:
        newMean = oldMean + 1/(n-1) * (curVal - oldMean)
        return newMean

    
eps = 0.00001
b = 50
maxiter = 1000000
mean = 0
corr = 0
stopcounter = 0

M = 0

#curVal == dice
i = 1.0 
#n == i

for i in range(1, maxiter+1):
    dice = np.random.randint(1,7) ##first dice throw == first mean
    if i == 1:
        M = dice
        M = getMeanFromReturns(M, i, dice)
        corr = 0  ## first corr == 0
    else:
        corr = ( ( dice - M) / i )
        M = getMeanFromReturns(M, i, dice)
        if abs(corr) < eps:
            stopcounter += 1
        else:
            stopcounter = 0
    if stopcounter >= b:
        break        
        
print('you did iterations == ', i)
print('mean == ', M)
print('corr == ', corr)    
    

you did iterations ==  250645
mean ==  3.4941590462967453
corr ==  -5.961279928187106e-06


In [6]:
#double checking the mean calculations in regular style

meanSum = 0
mean = 0
dice = 0
for i in range(1, maxiter +1):
    dice = np.random.randint(1,7)
    meanSum += dice
    mean = meanSum / i
    
    
print('real mean was ', mean)
print('wtf mate?! I thought that the mean was suppsoed to be \n \
close towards 3.0 or something like that, because the dice is from interval [1, 6] \n')

print('on the other hand, it is true that the expected value is supposed to be 1/6 * (1+2+3+4+5+6) = 3.5 \n \
as that is the correct formula, when I looked it up on wikipedia' )

print('on the other hand it does seem to make intuitive sense also \n \
if you draw the sequence of numbers [1, 2, 3, 4, 5, 6] \n \
then it is true that the 3.5 is basically the value in the center exactly speaking \n \
and with equally likely probability of each result in a dice roll, then I think 3.5 makes sense')

real mean was  3.500656
wtf mate?! I thought that the mean was suppsoed to be 
 close towards 3.0 or something like that, because the dice is from interval [1, 6] 

on the other hand, it is true that the expected value is supposed to be 1/6 * (1+2+3+4+5+6) = 3.5 
 as that is the correct formula, when I looked it up on wikipedia
on the other hand it does seem to make intuitive sense also 
 if you draw the sequence of numbers [1, 2, 3, 4, 5, 6] 
 then it is true that the 3.5 is basically the value in the center exactly speaking 
 and with equally likely probability of each result in a dice roll, then I think 3.5 makes sense


## Exercise 3

Given transition matrix P and initial state t0 write 
an iterative algorithm to find the steady state.

Stopping condition is that the norm (length of vector, use LA.norm) 
does not change more than eps in an iteration

In [7]:
maxiter = 10000
eps = 0.0000001

P = np.array(([0.2, 0.1, 0.7], [1.0, 0.0, 0.0], [0.2, 0.2, 0.6]))
t0 = np.array([1.0, 0.0, 0.0])

# YOUR CODE HERE
t_i = t0
t0Len = LA.norm(t0)
diff = 0

for i in range(1, maxiter + 1):
    t_iLen = LA.norm(t_i) ## store prev length
    t_i = np.dot(t_i, P) ##get new t_i vector, update it
    diff = LA.norm(t_i) - t_iLen ##compute the new diff based on prevNorm and curNorm
    if abs(diff) < eps:
        break

print('t_i == ', t_i )
print('')
print('diff == ', diff)
print('')
print('iterations == ', i)



t_i ==  [0.31250005 0.14062499 0.54687496]

diff ==  1.870303589779354e-08

iterations ==  13
